[server]
headless=true
enableXsrfProtection=false
enableCORS=false
sslCertFile = '/etc/letsencrypt/live/jou.mine.nu/fullchain.pem'
sslKeyFile = '/etc/letsencrypt/live/jou.mine.nu/privkey.pem'
[global]
developmentMode=false

